plugins { id 'com.android.application' }

android {
    namespace 'com.forcefocus.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.forcefocus.app'
        minSdk 23
        targetSdk 35
        versionCode 1601
        versionName '16.0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
    }
}

dependencies {}
